run:
  timeout: 3m
  tests: true
  build-tags:
    - unit
    - integration

output:
  formats:
    - format: colored-line-number
      path: stdout
    - format: html
      path: reports/golangci-lint.html
  uniq-by-line: false
  sort-results: true
  sort-order:
    - file
    - severity
    - linter
  show-stats: true

linters:
  enable-all: true
  disable:
    - gochecknoinits
    - goconst
    - godox
    - gomnd
    - execinquery
    - exhaustruct
    - wrapcheck
    - nolintlint  # Conflicts with gofmt

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  depguard:
    rules:
      main:
        files:
          - $all
        deny:
          - pkg: "github.com/pkg/errors"
            desc: Should be replaced by standard lib errors package
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/novoseltcev/go-course)
  goimports:
    local-prefixes: github.com/novoseltcev/go-course
  gosec:
    excludes:
      - G114
  ireturn:
    allow:
      - anon
      - error
      - empty
      - stdlib
      - generic
      - (or|er)$
  lll:
    line-length: 120
  misspell:
    locale: US
  mnd:
    ignored-numbers:
      - '0o666'
      - 1024
  stylecheck:
    checks:
      - ST1000
      # Dot imports are discouraged.
      # https://staticcheck.dev/docs/checks/#ST1001
      - ST1001
      # Poorly chosen identifier.
      # https://staticcheck.dev/docs/checks/#ST1003
      - ST1003
      # Incorrectly formatted error string.
      # https://staticcheck.dev/docs/checks/#ST1005
      - ST1005
      # Poorly chosen receiver name.
      # https://staticcheck.dev/docs/checks/#ST1006
      - ST1006
      # A function's error value should be its last return value.
      # https://staticcheck.dev/docs/checks/#ST1008
      - ST1008
      # Poorly chosen name for variable of type 'time.Duration'.
      # https://staticcheck.dev/docs/checks/#ST1011
      - ST1011
      # Poorly chosen name for error variable.
      # https://staticcheck.dev/docs/checks/#ST1012
      - ST1012
      # Should use constants for HTTP error codes, not magic numbers.
      # https://staticcheck.dev/docs/checks/#ST1013
      - ST1013
      # A switch's default case should be the first or last case.
      # https://staticcheck.dev/docs/checks/#ST1015
      - ST1015
      # Use consistent method receiver names.
      # https://staticcheck.dev/docs/checks/#ST1016
      - ST1016
      # Don't use Yoda conditions.
      # https://staticcheck.dev/docs/checks/#ST1017
      - ST1017
      # Avoid zero-width and control characters in string literals.
      # https://staticcheck.dev/docs/checks/#ST1018
      - ST1018
      # Importing the same package multiple times.
      # https://staticcheck.dev/docs/checks/#ST1019
      #- ST1019
      # The documentation of an exported function should start with the function's name.
      # https://staticcheck.dev/docs/checks/#ST1020
      - ST1020
      # The documentation of an exported type should start with type's name.
      # https://staticcheck.dev/docs/checks/#ST1021
      - ST1021
      # The documentation of an exported variable or constant should start with variable's name.
      # https://staticcheck.dev/docs/checks/#ST1022
      - ST1022
      # Redundant type in variable declaration.
      # https://staticcheck.dev/docs/checks/#ST1023
      - ST1023
  varnamelen:
    check-return: true
    ignore-type-assert-ok: true
    ignore-map-index-ok: true
    ignore-chan-recv-ok: true
    ignore-names:
      - err
      - tt
      - ch
      - id
      - fn
    ignore-decls:
      - b []byte
      - p []byte
      - i int
      - n int
      - v T
      - fd *os.File
      - fd afero.File
      - fs afero.Fs
      # sync
      - wg sync.WaitGroup
      - g *errgroup.Group
      # db
      - db *sqlx.DB
      - tx *sql.Tx
      # http
      - r *http.Request
      - w http.ResponseWriter
      - r *chi.Mux
      - r chi.Router
      # tests
      - t testing.T
      - b testing.B
      - ts *httptest.Server
      - m *migrate.Migrate
      # custom
      - c Client
      - km *chunkedrsa.KeyManager
  
issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - err113
        - errcheck
        - dupl
        - funlen
        - gochecknoglobals
        - gosec
        - unparam
        - wsl
    - linters:
        - lll
      source: "^//go:generate "
  exclude-generated: lax
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
