// Code generated by MockGen. DO NOT EDIT.
// Source: decrypt.go
//
// Generated by this command:
//
//	mockgen -source=decrypt.go -destination=./decrypt_mock_test.go -package=middlewares_test -typed
//

// Package middlewares_test is a generated GoMock package.
package middlewares_test

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Mockdecryptor is a mock of decryptor interface.
type Mockdecryptor struct {
	ctrl     *gomock.Controller
	recorder *MockdecryptorMockRecorder
	isgomock struct{}
}

// MockdecryptorMockRecorder is the mock recorder for Mockdecryptor.
type MockdecryptorMockRecorder struct {
	mock *Mockdecryptor
}

// NewMockdecryptor creates a new mock instance.
func NewMockdecryptor(ctrl *gomock.Controller) *Mockdecryptor {
	mock := &Mockdecryptor{ctrl: ctrl}
	mock.recorder = &MockdecryptorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockdecryptor) EXPECT() *MockdecryptorMockRecorder {
	return m.recorder
}

// Decrypt mocks base method.
func (m *Mockdecryptor) Decrypt(b []byte) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Decrypt", b)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Decrypt indicates an expected call of Decrypt.
func (mr *MockdecryptorMockRecorder) Decrypt(b any) *MockdecryptorDecryptCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Decrypt", reflect.TypeOf((*Mockdecryptor)(nil).Decrypt), b)
	return &MockdecryptorDecryptCall{Call: call}
}

// MockdecryptorDecryptCall wrap *gomock.Call
type MockdecryptorDecryptCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockdecryptorDecryptCall) Return(arg0 []byte, arg1 error) *MockdecryptorDecryptCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockdecryptorDecryptCall) Do(f func([]byte) ([]byte, error)) *MockdecryptorDecryptCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockdecryptorDecryptCall) DoAndReturn(f func([]byte) ([]byte, error)) *MockdecryptorDecryptCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
